import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useRef } from "react";
import profilePic from "public/images/profile/IMG_3431 --2.jpg";
import { useInView, useMotionValue, useSpring } from "framer-motion";
import Skills from "@/components/Skills";
import Experience from "@/components/Experience";
import Education from "@/components/Education";
import TransitionEffect from "@/components/TransitionEffect";

const AnimatedNumber = ({ number }) => {
  const ref = useRef(null);
  const motion = useMotionValue(0);
  const spring = useSpring(motion, { duration: 3000 });
  const isInView = useInView(ref, { once: true });
  useEffect(() => {
    if (isInView) {
      motion.set(number);
    }
  }, [isInView, number, motion]);

  useEffect(() => {
    spring.on("change", (latest) => {
      if (ref.current && latest.toFixed(0) <= number) {
        ref.current.textContent = latest.toFixed(0);
      }
    });
  }, [spring, number]);
  return <span ref={ref}></span>;
};

const AboutPage = () => {
  return (
    <>
      <Head>
        <title>About page - S.SATASIYA</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex dark:text-light w-full flex-col items-center justify-center">
        <Layout className="pt-16">
          <AnimatedText
            text={"Passion Fuels Purpose! "}
            className="mb-16 lg:!text-7xl  sm:!text-6xl xs:!text-4xl sm:mb-8"
          ></AnimatedText>
          <div className="grid w-full grid-cols-8 gap-16 sm:gap-8">
            <div className="col-span-3 flex flex-col items-start justify-start md:col-span-8 md:order-2 xl:col-span-4">
              <h2 className="mb-4 text-lg font-bold uppercase text-dark/75 dark:text-light/75">
                Biography
              </h2>
              <p className="font-medium">
                I am a dynamic full-stack developer fueled by a fervor for
                crafting innovative applications and unraveling complex
                challenges. My journey as a self-taught developer has been
                marked by an insatiable curiosity for learning, especially in
                the realms of cutting-edge technologies and frameworks.
              </p>

              <p className="my-4 font-medium">
                Driven by a passion for both functionality and aesthetic, I
                bring a keen interest in design and user experience to every
                project I undertake. I am a firm believer in the power of
                technology to transform the world, and I am committed to
                leveraging my skills to create a positive impact.
              </p>

              <p className="font-medium my-4">
                Embarking on this exhilarating coding odyssey, I am ceaselessly
                exploring new horizons in technology. As I navigate the
                ever-evolving landscape of web development, I am actively
                seeking fresh opportunities to contribute my expertise and make
                a meaningful impact.
              </p>

              <p className="font-medium">
                Let&apos;s shape the future of technology together.
              </p>
            </div>
            <div className="col-span-3 relative h-max md:order-1 md:col-span-8 xl:col-span-4 rounded-2xl border-2 border-solid border-dark bg-light dark:bg-dark dark:border-light p-8">
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light"></div>
              <Image
                src={profilePic}
                alt="Picture of the author"
                className="w-full h-auto rounded-2xl"
                priority={true}
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className="col-span-2 flex flex-col md:order-3 xl:col-span-8 xl:flex-row xl:items-center items-end justify-evenly">
              <div className="flex flex-col items-end justify-center xl:items-center">
                <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                  <AnimatedNumber number={20} />+
                </span>
                <h2 className="text-xl font-medium capitalize xl:text-center md:text-lg sm:text-base xs:text-sm dark:text-light/75 text-dark/75">
                  projects completed
                </h2>
              </div>
              <div className="flex flex-col items-end justify-center xl:items-center">
                <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                  <AnimatedNumber number={2} />+
                </span>
                <h2 className="text-xl font-medium capitalize xl:text-center md:text-lg sm:text-base xs:text-sm dark:text-light/75 text-dark/75">
                  {" "}
                  Years of experience
                </h2>
              </div>
              {/* <div className="flex flex-col items-end justify-center xl:items-center ">
                <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                  <AnimatedNumber number={50} />+
                </span>
                <h2 className="text-xl font-medium capitalize dark:text-light/75 text-dark/75 xl:text-center md:text-lg sm:text-base xs:text-sm">
                  satisfied clients
                </h2>
              </div> */}
            </div>
          </div>
          <Skills />
          <Experience />
          <Education />
        </Layout>
      </main>
    </>
  );
};

export default AboutPage;
