import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import profilepic from "../../public/images/profile/Img1.png";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkIcon } from "@/components/Icons";
import TransitionEffect from "@/components/TransitionEffect";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home page - S.SATASIYA</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col lg:text-center">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilepic}
                alt="Picture of the author"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority={true}
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              ></Image>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text={
                  "Empowering Ideas with Precision Coding and Intuitive Design."
                }
                className={
                  "!text-5xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
                }
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a results-driven software developer, I bring over a year of
                experience in crafting innovative web solutions. Join me on a
                journey through my portfolio, where you&apos;ll witness the
                fusion of precision coding and intuitive design.
              </p>
              <div className="items-center self-start flex mt-2 lg:self-center">
                <Link
                  href="/Resume.pdf"
                  target={"__blank"}
                  className="flex items-center justify-center md:px-4 md:text-base p-2.5 px-6 font-semibold hover:dark:bg-dark hover:dark:text-light hover:dark:border-light dark:text-dark dark:bg-light  text-white bg-dark rounded-lg hover:bg-light hover:text-dark border border-solid border-transparent hover:border-dark"
                >
                  Resume <LinkIcon className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:shyamsatasiya10@gmail.com"
                  target={"__blank"}
                  className="ml-4 text-lg dark:text-light font-medium capitalize md:text-base text-dark underline"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
